<?php
if(function_exists("register_field_group")) {
	register_field_group(array (
		'id' => 'acf_magic_user_admin_registration_page',
		'title' => 'Magic Registration Page',
		'fields' => array (
			array (
				'key' => 'field_5b3644536c379',
				'label' => 'Content above Form',
				'name' => 'above_form',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_5b36437571e86',
				'label' => 'Email Placeholder Text',
				'name' => 'email_placeholder',
				'type' => 'text',
				'default_value' => 'Your email',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b36439e71e87',
				'label' => 'Password Placeholder Text',
				'name' => 'password_placeholder',
				'type' => 'text',
				'default_value' => 'Password',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b3643b171e88',
				'label' => 'Password2 Placeholder Text',
				'name' => 'password2_placeholder',
				'type' => 'text',
				'default_value' => 'Password (again...)',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b364413cf3a5',
				'label' => 'Submit Button Text',
				'name' => 'submit_text',
				'type' => 'text',
				'default_value' => 'Submit',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b3644656c37a',
				'label' => 'Content Below Form',
				'name' => 'below_form',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'magic_user_admin_registration.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'categories',
				6 => 'tags',
				7 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
}
