<?php
if ( function_exists("register_field_group" ) ) {
	register_field_group(array (
		'id' => 'acf_magic_user_admin_profile_page',
		'title' => 'Magic User Profile Page',
		'fields' => array (
			array (
				'key' => 'field_5b376fc5d3ede',
				'label' => 'Text above Form',
				'name' => 'above_text',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array(
				'key' => 'magic_user_admin_profile_page_use_gravatar',
				'label' => 'Use Gravatar images',
				'name' => 'use_gravatar',
				'type' => 'true_false',
				'message' => 'Load user images using gravatar',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5b376fe0d3edf',
				'label' => 'Login text',
				'name' => 'login_text',
				'type' => 'text',
				'default_value' => 'Login',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b376fed72275',
				'label' => 'Display name text',
				'name' => 'display_name_text',
				'type' => 'text',
				'default_value' => 'Display name',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b376ffc3758d',
				'label' => 'Nicename text',
				'name' => 'nicename_text',
				'type' => 'text',
				'default_value' => 'Full name',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b377028ee3af',
				'label' => 'Email text',
				'name' => 'email_text',
				'type' => 'text',
				'default_value' => 'Email',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b377049cfa80',
				'label' => 'Url text',
				'name' => 'url_text',
				'type' => 'text',
				'default_value' => 'Your Homepage',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b377086aeece',
				'label' => 'Registered at text',
				'name' => 'registered_text',
				'type' => 'text',
				'default_value' => 'Registered at',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b37704dcfa80',
				'label' => 'Submit button text',
				'name' => 'submit_text',
				'type' => 'text',
				'default_value' => 'Submit',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b37709e6ed98',
				'label' => 'Text below Form',
				'name' => 'below_text',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'magic_user_admin_profile.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'categories',
				6 => 'tags',
				7 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
}
